/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedSettingsTemplatesRouteImport } from './routes/_authenticated/settings.templates'
import { Route as AuthenticatedSettingsBrandRouteImport } from './routes/_authenticated/settings.brand'
import { Route as AuthenticatedSettingsAiRouteImport } from './routes/_authenticated/settings.ai'
import { Route as AuthenticatedProjectsNewRouteImport } from './routes/_authenticated/projects.new'
import { Route as AuthenticatedProjectsIdRouteImport } from './routes/_authenticated/projects.$id'
import { Route as ApiJobsRunJobIdRouteImport } from './routes/api/jobs/run.$jobId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsTemplatesRoute =
  AuthenticatedSettingsTemplatesRouteImport.update({
    id: '/settings/templates',
    path: '/settings/templates',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsBrandRoute =
  AuthenticatedSettingsBrandRouteImport.update({
    id: '/settings/brand',
    path: '/settings/brand',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsAiRoute = AuthenticatedSettingsAiRouteImport.update({
  id: '/settings/ai',
  path: '/settings/ai',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectsNewRoute =
  AuthenticatedProjectsNewRouteImport.update({
    id: '/projects/new',
    path: '/projects/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsIdRoute = AuthenticatedProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiJobsRunJobIdRoute = ApiJobsRunJobIdRouteImport.update({
  id: '/api/jobs/run/$jobId',
  path: '/api/jobs/run/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/projects/new': typeof AuthenticatedProjectsNewRoute
  '/settings/ai': typeof AuthenticatedSettingsAiRoute
  '/settings/brand': typeof AuthenticatedSettingsBrandRoute
  '/settings/templates': typeof AuthenticatedSettingsTemplatesRoute
  '/api/jobs/run/$jobId': typeof ApiJobsRunJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/projects/new': typeof AuthenticatedProjectsNewRoute
  '/settings/ai': typeof AuthenticatedSettingsAiRoute
  '/settings/brand': typeof AuthenticatedSettingsBrandRoute
  '/settings/templates': typeof AuthenticatedSettingsTemplatesRoute
  '/api/jobs/run/$jobId': typeof ApiJobsRunJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/_authenticated/projects/new': typeof AuthenticatedProjectsNewRoute
  '/_authenticated/settings/ai': typeof AuthenticatedSettingsAiRoute
  '/_authenticated/settings/brand': typeof AuthenticatedSettingsBrandRoute
  '/_authenticated/settings/templates': typeof AuthenticatedSettingsTemplatesRoute
  '/api/jobs/run/$jobId': typeof ApiJobsRunJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/projects/$id'
    | '/projects/new'
    | '/settings/ai'
    | '/settings/brand'
    | '/settings/templates'
    | '/api/jobs/run/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/projects/$id'
    | '/projects/new'
    | '/settings/ai'
    | '/settings/brand'
    | '/settings/templates'
    | '/api/jobs/run/$jobId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/projects/$id'
    | '/_authenticated/projects/new'
    | '/_authenticated/settings/ai'
    | '/_authenticated/settings/brand'
    | '/_authenticated/settings/templates'
    | '/api/jobs/run/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiJobsRunJobIdRoute: typeof ApiJobsRunJobIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/templates': {
      id: '/_authenticated/settings/templates'
      path: '/settings/templates'
      fullPath: '/settings/templates'
      preLoaderRoute: typeof AuthenticatedSettingsTemplatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/brand': {
      id: '/_authenticated/settings/brand'
      path: '/settings/brand'
      fullPath: '/settings/brand'
      preLoaderRoute: typeof AuthenticatedSettingsBrandRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/ai': {
      id: '/_authenticated/settings/ai'
      path: '/settings/ai'
      fullPath: '/settings/ai'
      preLoaderRoute: typeof AuthenticatedSettingsAiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/new': {
      id: '/_authenticated/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof AuthenticatedProjectsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$id': {
      id: '/_authenticated/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof AuthenticatedProjectsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/jobs/run/$jobId': {
      id: '/api/jobs/run/$jobId'
      path: '/api/jobs/run/$jobId'
      fullPath: '/api/jobs/run/$jobId'
      preLoaderRoute: typeof ApiJobsRunJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProjectsIdRoute: typeof AuthenticatedProjectsIdRoute
  AuthenticatedProjectsNewRoute: typeof AuthenticatedProjectsNewRoute
  AuthenticatedSettingsAiRoute: typeof AuthenticatedSettingsAiRoute
  AuthenticatedSettingsBrandRoute: typeof AuthenticatedSettingsBrandRoute
  AuthenticatedSettingsTemplatesRoute: typeof AuthenticatedSettingsTemplatesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProjectsIdRoute: AuthenticatedProjectsIdRoute,
  AuthenticatedProjectsNewRoute: AuthenticatedProjectsNewRoute,
  AuthenticatedSettingsAiRoute: AuthenticatedSettingsAiRoute,
  AuthenticatedSettingsBrandRoute: AuthenticatedSettingsBrandRoute,
  AuthenticatedSettingsTemplatesRoute: AuthenticatedSettingsTemplatesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiJobsRunJobIdRoute: ApiJobsRunJobIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
