/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as ApiPublicRenderCallbackRouteImport } from './routes/api/public/render-callback'
import { Route as AuthenticatedSettingsTemplatesRouteImport } from './routes/_authenticated/settings.templates'
import { Route as AuthenticatedSettingsRenderProvidersRouteImport } from './routes/_authenticated/settings.render-providers'
import { Route as AuthenticatedSettingsBrandRouteImport } from './routes/_authenticated/settings.brand'
import { Route as AuthenticatedSettingsAiRouteImport } from './routes/_authenticated/settings.ai'
import { Route as AuthenticatedProjectsNewRouteImport } from './routes/_authenticated/projects.new'
import { Route as AuthenticatedProjectsIdRouteImport } from './routes/_authenticated/projects.$id'
import { Route as ApiPublicRenderCallbackCreatomateRouteImport } from './routes/api/public/render-callback.creatomate'
import { Route as ApiJobsRunJobIdRouteImport } from './routes/api/jobs/run.$jobId'
import { Route as ApiPublicJobsRunJobIdRouteImport } from './routes/api/public/jobs/run.$jobId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicRenderCallbackRoute = ApiPublicRenderCallbackRouteImport.update({
  id: '/api/public/render-callback',
  path: '/api/public/render-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsTemplatesRoute =
  AuthenticatedSettingsTemplatesRouteImport.update({
    id: '/settings/templates',
    path: '/settings/templates',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsRenderProvidersRoute =
  AuthenticatedSettingsRenderProvidersRouteImport.update({
    id: '/settings/render-providers',
    path: '/settings/render-providers',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsBrandRoute =
  AuthenticatedSettingsBrandRouteImport.update({
    id: '/settings/brand',
    path: '/settings/brand',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsAiRoute = AuthenticatedSettingsAiRouteImport.update({
  id: '/settings/ai',
  path: '/settings/ai',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjectsNewRoute =
  AuthenticatedProjectsNewRouteImport.update({
    id: '/projects/new',
    path: '/projects/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsIdRoute = AuthenticatedProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicRenderCallbackCreatomateRoute =
  ApiPublicRenderCallbackCreatomateRouteImport.update({
    id: '/creatomate',
    path: '/creatomate',
    getParentRoute: () => ApiPublicRenderCallbackRoute,
  } as any)
const ApiJobsRunJobIdRoute = ApiJobsRunJobIdRouteImport.update({
  id: '/api/jobs/run/$jobId',
  path: '/api/jobs/run/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicJobsRunJobIdRoute = ApiPublicJobsRunJobIdRouteImport.update({
  id: '/api/public/jobs/run/$jobId',
  path: '/api/public/jobs/run/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/projects/new': typeof AuthenticatedProjectsNewRoute
  '/settings/ai': typeof AuthenticatedSettingsAiRoute
  '/settings/brand': typeof AuthenticatedSettingsBrandRoute
  '/settings/render-providers': typeof AuthenticatedSettingsRenderProvidersRoute
  '/settings/templates': typeof AuthenticatedSettingsTemplatesRoute
  '/api/public/render-callback': typeof ApiPublicRenderCallbackRouteWithChildren
  '/api/jobs/run/$jobId': typeof ApiJobsRunJobIdRoute
  '/api/public/render-callback/creatomate': typeof ApiPublicRenderCallbackCreatomateRoute
  '/api/public/jobs/run/$jobId': typeof ApiPublicJobsRunJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/projects/new': typeof AuthenticatedProjectsNewRoute
  '/settings/ai': typeof AuthenticatedSettingsAiRoute
  '/settings/brand': typeof AuthenticatedSettingsBrandRoute
  '/settings/render-providers': typeof AuthenticatedSettingsRenderProvidersRoute
  '/settings/templates': typeof AuthenticatedSettingsTemplatesRoute
  '/api/public/render-callback': typeof ApiPublicRenderCallbackRouteWithChildren
  '/api/jobs/run/$jobId': typeof ApiJobsRunJobIdRoute
  '/api/public/render-callback/creatomate': typeof ApiPublicRenderCallbackCreatomateRoute
  '/api/public/jobs/run/$jobId': typeof ApiPublicJobsRunJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/_authenticated/projects/new': typeof AuthenticatedProjectsNewRoute
  '/_authenticated/settings/ai': typeof AuthenticatedSettingsAiRoute
  '/_authenticated/settings/brand': typeof AuthenticatedSettingsBrandRoute
  '/_authenticated/settings/render-providers': typeof AuthenticatedSettingsRenderProvidersRoute
  '/_authenticated/settings/templates': typeof AuthenticatedSettingsTemplatesRoute
  '/api/public/render-callback': typeof ApiPublicRenderCallbackRouteWithChildren
  '/api/jobs/run/$jobId': typeof ApiJobsRunJobIdRoute
  '/api/public/render-callback/creatomate': typeof ApiPublicRenderCallbackCreatomateRoute
  '/api/public/jobs/run/$jobId': typeof ApiPublicJobsRunJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/projects/$id'
    | '/projects/new'
    | '/settings/ai'
    | '/settings/brand'
    | '/settings/render-providers'
    | '/settings/templates'
    | '/api/public/render-callback'
    | '/api/jobs/run/$jobId'
    | '/api/public/render-callback/creatomate'
    | '/api/public/jobs/run/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/projects/$id'
    | '/projects/new'
    | '/settings/ai'
    | '/settings/brand'
    | '/settings/render-providers'
    | '/settings/templates'
    | '/api/public/render-callback'
    | '/api/jobs/run/$jobId'
    | '/api/public/render-callback/creatomate'
    | '/api/public/jobs/run/$jobId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/projects/$id'
    | '/_authenticated/projects/new'
    | '/_authenticated/settings/ai'
    | '/_authenticated/settings/brand'
    | '/_authenticated/settings/render-providers'
    | '/_authenticated/settings/templates'
    | '/api/public/render-callback'
    | '/api/jobs/run/$jobId'
    | '/api/public/render-callback/creatomate'
    | '/api/public/jobs/run/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicRenderCallbackRoute: typeof ApiPublicRenderCallbackRouteWithChildren
  ApiJobsRunJobIdRoute: typeof ApiJobsRunJobIdRoute
  ApiPublicJobsRunJobIdRoute: typeof ApiPublicJobsRunJobIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/render-callback': {
      id: '/api/public/render-callback'
      path: '/api/public/render-callback'
      fullPath: '/api/public/render-callback'
      preLoaderRoute: typeof ApiPublicRenderCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/templates': {
      id: '/_authenticated/settings/templates'
      path: '/settings/templates'
      fullPath: '/settings/templates'
      preLoaderRoute: typeof AuthenticatedSettingsTemplatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/render-providers': {
      id: '/_authenticated/settings/render-providers'
      path: '/settings/render-providers'
      fullPath: '/settings/render-providers'
      preLoaderRoute: typeof AuthenticatedSettingsRenderProvidersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/brand': {
      id: '/_authenticated/settings/brand'
      path: '/settings/brand'
      fullPath: '/settings/brand'
      preLoaderRoute: typeof AuthenticatedSettingsBrandRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/ai': {
      id: '/_authenticated/settings/ai'
      path: '/settings/ai'
      fullPath: '/settings/ai'
      preLoaderRoute: typeof AuthenticatedSettingsAiRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/new': {
      id: '/_authenticated/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof AuthenticatedProjectsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$id': {
      id: '/_authenticated/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof AuthenticatedProjectsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/render-callback/creatomate': {
      id: '/api/public/render-callback/creatomate'
      path: '/creatomate'
      fullPath: '/api/public/render-callback/creatomate'
      preLoaderRoute: typeof ApiPublicRenderCallbackCreatomateRouteImport
      parentRoute: typeof ApiPublicRenderCallbackRoute
    }
    '/api/jobs/run/$jobId': {
      id: '/api/jobs/run/$jobId'
      path: '/api/jobs/run/$jobId'
      fullPath: '/api/jobs/run/$jobId'
      preLoaderRoute: typeof ApiJobsRunJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/run/$jobId': {
      id: '/api/public/jobs/run/$jobId'
      path: '/api/public/jobs/run/$jobId'
      fullPath: '/api/public/jobs/run/$jobId'
      preLoaderRoute: typeof ApiPublicJobsRunJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProjectsIdRoute: typeof AuthenticatedProjectsIdRoute
  AuthenticatedProjectsNewRoute: typeof AuthenticatedProjectsNewRoute
  AuthenticatedSettingsAiRoute: typeof AuthenticatedSettingsAiRoute
  AuthenticatedSettingsBrandRoute: typeof AuthenticatedSettingsBrandRoute
  AuthenticatedSettingsRenderProvidersRoute: typeof AuthenticatedSettingsRenderProvidersRoute
  AuthenticatedSettingsTemplatesRoute: typeof AuthenticatedSettingsTemplatesRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProjectsIdRoute: AuthenticatedProjectsIdRoute,
  AuthenticatedProjectsNewRoute: AuthenticatedProjectsNewRoute,
  AuthenticatedSettingsAiRoute: AuthenticatedSettingsAiRoute,
  AuthenticatedSettingsBrandRoute: AuthenticatedSettingsBrandRoute,
  AuthenticatedSettingsRenderProvidersRoute:
    AuthenticatedSettingsRenderProvidersRoute,
  AuthenticatedSettingsTemplatesRoute: AuthenticatedSettingsTemplatesRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ApiPublicRenderCallbackRouteChildren {
  ApiPublicRenderCallbackCreatomateRoute: typeof ApiPublicRenderCallbackCreatomateRoute
}

const ApiPublicRenderCallbackRouteChildren: ApiPublicRenderCallbackRouteChildren =
  {
    ApiPublicRenderCallbackCreatomateRoute:
      ApiPublicRenderCallbackCreatomateRoute,
  }

const ApiPublicRenderCallbackRouteWithChildren =
  ApiPublicRenderCallbackRoute._addFileChildren(
    ApiPublicRenderCallbackRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicRenderCallbackRoute: ApiPublicRenderCallbackRouteWithChildren,
  ApiJobsRunJobIdRoute: ApiJobsRunJobIdRoute,
  ApiPublicJobsRunJobIdRoute: ApiPublicJobsRunJobIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
