
ALTER TABLE public.project_context
  ADD COLUMN IF NOT EXISTS presenter_name TEXT,
  ADD COLUMN IF NOT EXISTS grounding_mode TEXT NOT NULL DEFAULT 'strict';

ALTER TABLE public.projects
  ADD COLUMN IF NOT EXISTS width INTEGER,
  ADD COLUMN IF NOT EXISTS height INTEGER,
  ADD COLUMN IF NOT EXISTS fps NUMERIC,
  ADD COLUMN IF NOT EXISTS file_size BIGINT;
